spring:
    application:
        name: template
    config:
        import:
            - classpath:/yml/application-secret.yml
        profiles:
            include: secret

        # mysql 데이터 베이스
        datasource:
            url: jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            username: root
            password: ${DB_PASSWORD}
            driver-class-name: com.mysql.cj.jdbc.Driver
        jpa:
            hibernate:
                ddl-auto: update
            show-sql: true
            properties:
                hibernate:
                    format_sql: true
                    dialect: org.hibernate.dialect.MySQL8Dialect
# application.yml
swagger:
    title: "프로젝트명 API"
    description: "프로젝트 설명을 여기에 작성합니다"
    version: "1.0.0"
    external-docs-description: "프로젝트명 API 문서"