spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: "jdbc:mysql://localhost:3306/fastsns"
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true