# Grafana 데이터소스 자동 설정
apiVersion: 1

datasources:
  - name: Prometheus                    # 데이터소스 이름
    type: prometheus                    # 데이터소스 타입
    access: proxy                       # 접근 방식 (Grafana 서버를 통해 접근)
    url: http://prometheus:9090         # Prometheus 주소 (Docker 네트워크)
    isDefault: true                     # 기본 데이터소스로 설정
    editable: true                      # 나중에 수정 가능